/*
 * The map itself: the basemap style, layer ordering, and the three things
 * layered onto the basemap that are not data — the label toggle, the shaded
 * relief and the 3D view.
 *
 * The GLACE rasters and the glacier inventories are PMTiles archives read
 * straight from object storage over HTTP range requests. The basemap and the
 * terrain instead read from tile endpoints, each declared to MapLibre as a
 * TileJSON document: the Protomaps hosted API for the basemap, and Mapterhorn
 * for the terrain — Mapterhorn also publishes PMTiles, but only up to z12 in
 * one archive, and its download server answers ranges uncached, where its zxy
 * endpoint covers every zoom and is edge-cached; the hillshade and the 3D mesh
 * read that instead, from one shared source.
 */

import {
  BASEMAP_ASSETS,
  BASEMAP_FLAVOR,
  BASEMAP_URL,
  INITIAL_VIEW,
  TERRAIN_TILEJSON,
  WORLD_IMAGERY_URL,
} from "./config.js";
import { cogRgbProtocol } from "./cog-rgb.js";
import { installSky } from "./sky.js";
import { setStatus } from "./ui.js";

/* `metadata: true` so each archive's own TileJSON reaches MapLibre, which is
 * what carries its attribution. Costs one small read per archive. */
maplibregl.addProtocol("pmtiles", new pmtiles.Protocol({ metadata: true }).tile);

/* The float COGs, read and coloured in the browser. Nothing on the page
 * produces a `glace-rgb://` source today; registering is free, and the reader
 * is not fetched until a tile is asked for — see js/cog-rgb.js and AGENTS.md. */
maplibregl.addProtocol("glace-rgb", cogRgbProtocol);

/* The basemap style is generated by @protomaps/basemaps rather than hand-written:
 * 69 layers, 13 of them labels, and the flavor decides every colour. Data layers
 * are inserted below its first symbol layer — see addStacked() below.
 *
 * Every flavor's labels are greys a step or two from their ground, drawn for a
 * map that is nothing but that ground. Here the ground is a GLACE raster
 * through cmc.lipari or grayC, and a grey label over it is lost, so every
 * label face is pushed to the flavor's extreme — white over a black halo on
 * the dark flavors, black over a white halo on the light ones. This is done in
 * the flavor, which is what the generator reads its label paint from, not by
 * patching the layers after: the generator's own halo is 1 px and unblurred,
 * and a wider, blurred one drew a grey ring around small labels. Water labels
 * keep their halo in the water colour (the generator's rule, no field for it),
 * and POIs keep their kind colours; both are fine where they are. */
const DARK_FLAVORS = new Set(["black", "dark"]);
const LABEL_FIELDS = [
  "roads_label_minor",
  "roads_label_major",
  "ocean_label",
  "subplace_label",
  "city_label",
  "state_label",
  "country_label",
  "address_label",
];
// A copy: namedFlavor() hands back the library's own object.
const flavor = { ...basemaps.namedFlavor(BASEMAP_FLAVOR) };
const [labelFace, labelHalo] = DARK_FLAVORS.has(BASEMAP_FLAVOR)
  ? ["#f8fafc", "#000000"]
  : ["#000000", "#ffffff"];
for (const field of LABEL_FIELDS) {
  flavor[field] = labelFace;
  if (`${field}_halo` in flavor) flavor[`${field}_halo`] = labelHalo;
}
const basemapLayers = basemaps.layers("protomaps", flavor, { lang: "en" });
const style = {
  version: 8,
  /* `globe` is not "always a globe": MapLibre expands the bare type into a zoom
   * interpolation — vertical-perspective at z11, mercator from z12 — so the
   * earth is round while the whole arc is in view and flat by the time anyone
   * is reading a glacier. Terrain works under it, so the 3D button costs
   * nothing. */
  projection: { type: "globe" },
  glyphs: `${BASEMAP_ASSETS}/fonts/{fontstack}/{range}.pbf`,
  sprite: `${BASEMAP_ASSETS}/sprites/v4/${BASEMAP_FLAVOR}`,
  sources: {
    protomaps: {
      type: "vector",
      url: BASEMAP_URL,
      /* The data and its publisher, in one string deliberately: MapLibre sorts
       * attributions by length before joining them, so two entries would be
       * scattered through the line at lengths nobody controls, while one keeps
       * its own order. The renderer's credit is *not* here — it belongs to no
       * source, so it rides on the control below. */
      attribution:
        '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>' +
        ' | <a href="https://protomaps.com">Protomaps</a>',
    },
  },
  layers: basemapLayers,
};

/* The vector basemap can be replaced by imagery without replacing the whole
 * style (which would discard every lazily added data layer). Remember the
 * original visibility of its non-label layers so switching back restores the
 * generated Protomaps style exactly. Symbols are intentionally excluded: the
 * separate label checkbox controls them, including over World Imagery. */
const VECTOR_BASEMAP_LAYERS = new Map(
  style.layers
    .filter((layer) => layer.type !== "symbol")
    .map((layer) => [layer.id, layer.layout?.visibility ?? "visible"]),
);
const WORLD_IMAGERY_SOURCE = "world-imagery";
const WORLD_IMAGERY_LAYER = "world-imagery";

/* Without WebGL2 the constructor throws, and every module below depends on
 * the map, so the page ends here: the status line says why, then the error
 * goes on to the console. */
function createMap() {
  try {
    return new maplibregl.Map({
      container: "map",
      style,
      center: INITIAL_VIEW.center,
      zoom: INITIAL_VIEW.zoom,
      minZoom: INITIAL_VIEW.minZoom,
      maxZoom: INITIAL_VIEW.maxZoom,
      // The view lives in the URL, so a hash overrides the opening view above.
      hash: true,
      attributionControl: false,
    });
  } catch (error) {
    setStatus("map", "This browser cannot draw the map: it has no WebGL2.", "error");
    throw error;
  }
}

export const map = createMap();
/* The halo around the globe, painted by style.css from the numbers this keeps
 * on #map. See js/sky.js. */
installSky(map, map.getContainer());
map.addControl(new maplibregl.NavigationControl({ visualizePitch: false }), "top-right");
// The panel is above this corner, and on a short viewport it would reach it —
// #panel-shell in style.css stops short of the bottom by exactly the room this
// needs, so the two have to agree.
map.addControl(new maplibregl.ScaleControl({ maxWidth: 120, unit: "metric" }), "bottom-left");
map.addControl(
  new maplibregl.AttributionControl({
    compact: true,
    /* The renderer is drawing whether or not any basemap is, so its credit hangs
     * off the control rather than off a source. It used to ride in both basemap
     * sources' strings, and a source only receives its attribution once its
     * TileJSON resolves — so a blocked request took the renderer's credit with
     * the basemap's. Being the shortest entry, it now sorts to the front. */
    customAttribution: '<a href="https://maplibre.org">MapLibre</a>',
  }),
  "bottom-right",
);

map.on("error", (event) => {
  if (event.error) console.warn("maplibre:", event.error.message);
});

/* `load` fires exactly once, and only when every source has finished loading —
 * which the first data layer immediately undoes, so from then on
 * `isStyleLoaded()` is false while tiles stream but `load` can never fire again.
 * Anything waiting on it in that window waits forever. Adding a source needs
 * only the style to be parsed, which is what `style.load` reports; the promise
 * is built here, before the style can possibly have loaded.
 *
 * Every control that touches the map awaits this, which is also what makes the
 * page usable while the basemap is still coming down: a box ticked during those
 * first seconds is honoured when the style arrives instead of being dropped. */
export const styleReady = new Promise((resolve) => map.once("style.load", resolve));

/* ---------- layer ordering ---------- */

function firstSymbolLayer() {
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol") return layer.id;
  }
  return undefined;
}

/* Draw order, bottom to top:
 *
 *   basemap fills · GLACE rasters · hillshade · vector overlays · basemap labels
 *
 * Everything above the basemap is created lazily, the first time its control is
 * switched on, so the layers arrive in whatever order the reader clicks. That
 * makes "whichever was added last ends up on top" useless as a stacking rule:
 * shaded relief has to sit over the data whether the box was ticked before or
 * after a year was chosen, and glacier outlines have to sit over the relief.
 *
 * So each layer says what kind it is instead, and is inserted before the lowest
 * layer already on the map that must stay above it — falling through to the
 * basemap's first symbol layer, which is what keeps the labels on top of all of
 * it. */
const STACK = ["data", "hillshade", "overlay"];

/* Layer id -> kind. Entries for removed layers are left behind rather than
 * swept: the lookup only ever asks about ids the style still has. */
const layerKinds = new Map();

export function addStacked(kind, layer) {
  const above = STACK.slice(STACK.indexOf(kind) + 1);
  const before =
    map.getStyle().layers.find((other) => above.includes(layerKinds.get(other.id)))?.id ??
    firstSymbolLayer();
  map.addLayer(layer, before);
  layerKinds.set(layer.id, kind);
}

/* ---------- basemap ---------- */

function ensureWorldImagery() {
  if (!map.getSource(WORLD_IMAGERY_SOURCE)) {
    map.addSource(WORLD_IMAGERY_SOURCE, {
      type: "raster",
      tiles: [WORLD_IMAGERY_URL],
      tileSize: 256,
      maxzoom: 19,
      // Declared because a `tiles:` template has no TileJSON to inherit from.
      // "© Esri", not Esri's own "Tiles © Esri", to read as the others do.
      attribution: "© Esri, Maxar, Earthstar Geographics, and the GIS User Community",
    });
  }
  if (!map.getLayer(WORLD_IMAGERY_LAYER)) {
    /* Below the first generated basemap layer, so imagery remains the floor of
     * the stack and GLACE data, relief, overlays and labels all stay above it. */
    map.addLayer(
      {
        id: WORLD_IMAGERY_LAYER,
        type: "raster",
        source: WORLD_IMAGERY_SOURCE,
        layout: { visibility: "none" },
      },
      map.getStyle().layers[0]?.id,
    );
  }
}

export async function setBasemap(value) {
  await styleReady;
  const imagery = value === "imagery";
  if (imagery) ensureWorldImagery();
  for (const [id, visibility] of VECTOR_BASEMAP_LAYERS) {
    map.setLayoutProperty(id, "visibility", imagery ? "none" : visibility);
  }
  if (map.getLayer(WORLD_IMAGERY_LAYER)) {
    map.setLayoutProperty(WORLD_IMAGERY_LAYER, "visibility", imagery ? "visible" : "none");
  }
  /* The labels are not repainted for imagery: white on black or black on
   * white reads over snow and forest alike. */
}

/* ---------- basemap labels ---------- */

/* The basemap's symbol layers are the only ones that compete with the data for
 * legibility, so the toggle hides those rather than the whole basemap. */
export async function toggleBasemapLabels(on) {
  await styleReady;
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol" && layer.source === "protomaps") {
      map.setLayoutProperty(layer.id, "visibility", on ? "visible" : "none");
    }
  }
}

/* ---------- terrain ---------- */

/* One `raster-dem` source feeds both the shaded relief and the 3D mesh, so
 * whichever is switched on first pays for the tilejson and the tiles and the
 * other rides along. Created on first use rather than at startup: it is a
 * network cost nobody who leaves both switched off should pay. */
const TERRAIN_SOURCE = "terrain";

function ensureTerrainSource() {
  if (map.getSource(TERRAIN_SOURCE)) return;
  /* No `attribution`: Mapterhorn's TileJSON carries its own, and a spec that
   * names one would override it. Still shown only while the DEM is drawn — by
   * the hillshade or by 3D — since MapLibre keys that on the source. */
  map.addSource(TERRAIN_SOURCE, { type: "raster-dem", url: TERRAIN_TILEJSON });
}

/* ---------- hillshade ---------- */

const HILLSHADE_LAYER = "hillshade";

const hillshade = { on: false, strength: 0.55 };

/* MapLibre has no layer blend modes, so a literal "multiply" is not available.
 * The equivalent for shaded relief is a hillshade whose highlights are fully
 * transparent and whose shadows are black: lit slopes leave the data untouched
 * and shaded slopes darken it, which is what multiplying by a shading layer
 * does. There is no `hillshade-opacity` either, so the strength slider drives
 * the alpha of the shadow and accent colours. */
function hillshadePaint(strength) {
  return {
    "hillshade-method": "igor",
    "hillshade-illumination-direction": 315,
    "hillshade-exaggeration": 0.5,
    "hillshade-highlight-color": "rgba(255, 255, 255, 0)",
    "hillshade-shadow-color": `rgba(0, 0, 0, ${strength.toFixed(3)})`,
    "hillshade-accent-color": `rgba(0, 0, 0, ${(strength * 0.5).toFixed(3)})`,
  };
}

function ensureHillshade() {
  if (map.getLayer(HILLSHADE_LAYER)) return;
  ensureTerrainSource();
  addStacked("hillshade", {
    id: HILLSHADE_LAYER,
    type: "hillshade",
    source: TERRAIN_SOURCE,
    layout: { visibility: "none" },
    paint: hillshadePaint(hillshade.strength),
  });
}

export async function setHillshade(on) {
  hillshade.on = on;
  await applyHillshade();
}

export async function setHillshadeStrength(strength) {
  hillshade.strength = strength;
  await applyHillshade();
}

async function applyHillshade() {
  await styleReady;
  // Nothing to create while the box has never been ticked, and nothing to
  // update either — the paint is read when the layer is finally built.
  if (!hillshade.on && !map.getLayer(HILLSHADE_LAYER)) return;
  ensureHillshade();
  map.setLayoutProperty(HILLSHADE_LAYER, "visibility", hillshade.on ? "visible" : "none");
  for (const [property, value] of Object.entries(hillshadePaint(hillshade.strength))) {
    map.setPaintProperty(HILLSHADE_LAYER, property, value);
  }
}

/* ---------- 3D ---------- */

/* Enabling 3D drapes the map over the DEM and tilts the camera in one gesture,
 * and disabling it puts the camera back flat — the behaviour the button
 * promises, rather than terrain quietly switched on under an unchanged
 * overhead view where it would be invisible. The tilt is animated because the
 * jump reads as the page reloading.
 *
 * 60° is MapLibre's default `maxPitch`, so the slant does not need the map to
 * be constructed with a raised limit. */
const THREE_D_PITCH = 60;
const THREE_D_DURATION_MS = 600;
const TERRAIN_EXAGGERATION = 1;

const view = { threeD: false };
let threeDButton = null;

/* `tilt: false` switches the mesh without moving the camera, which is what the
 * restore at the bottom of this file needs: the pitch is already where the
 * #hash put it, and easing to 60° would round every shared link off to the
 * same view. Pressing the button always tilts. */
export async function setThreeD(on, { tilt = true } = {}) {
  view.threeD = on;
  syncThreeDButton();
  await styleReady;
  if (on) {
    ensureTerrainSource();
    map.setTerrain({ source: TERRAIN_SOURCE, exaggeration: TERRAIN_EXAGGERATION });
  } else {
    // Terrain is dropped, but the source stays for the hillshade and for the
    // next time the button is pressed.
    map.setTerrain(null);
  }
  // The mesh is raised before the camera moves, so the tilt does not play out
  // over a surface that is still flat.
  if (tilt) map.easeTo({ pitch: on ? THREE_D_PITCH : 0, duration: THREE_D_DURATION_MS });
}

/* MapLibre ships a `TerrainControl`, but it draws a mountain glyph and only
 * flips `setTerrain`. This is the same button with the label the design asks
 * for and the camera move above. It borrows MapLibre's own control classes, so
 * it renders as one more button in the stack under the navigation control
 * rather than as something bolted beside it. */
class ThreeDControl {
  onAdd() {
    this.container = document.createElement("div");
    this.container.className = "maplibregl-ctrl maplibregl-ctrl-group";
    threeDButton = document.createElement("button");
    threeDButton.type = "button";
    threeDButton.className = "maplibregl-ctrl-3d";
    threeDButton.addEventListener("click", () => setThreeD(!view.threeD));
    this.container.append(threeDButton);
    syncThreeDButton();
    return this.container;
  }

  onRemove() {
    this.container.remove();
    threeDButton = null;
  }
}

/* The button names what the next press does, not the state it is in: "3D"
 * while the map is flat, "2D" once it is tilted. */
function syncThreeDButton() {
  if (!threeDButton) return;
  const action = view.threeD ? "Disable 3D terrain" : "Enable 3D terrain";
  threeDButton.textContent = view.threeD ? "2D" : "3D";
  threeDButton.title = action;
  threeDButton.setAttribute("aria-label", action);
  threeDButton.setAttribute("aria-pressed", String(view.threeD));
}

map.addControl(new ThreeDControl(), "top-right");

/* The view lives in the #hash, pitch included, so a link copied while tilted
 * comes back tilted. Terrain is not in the hash, so without this the recipient
 * would get the slant with a flat surface under it. */
if (map.getPitch() > 0) setThreeD(true, { tilt: false });
