/*
 * The map itself: the basemap style, layer ordering, and the three things
 * layered onto the basemap that are not data — the label toggle, the shaded
 * relief and the 3D view.
 *
 * The GLACE rasters and the glacier inventories are PMTiles archives read
 * straight from object storage over HTTP range requests. The basemap and the
 * terrain instead read from tile endpoints, each declared to MapLibre as a
 * TileJSON document: the Protomaps hosted API for the basemap, and Mapterhorn
 * for the terrain — Mapterhorn also publishes PMTiles, but only up to z12 in
 * one archive, and its download server answers ranges uncached, where its zxy
 * endpoint covers every zoom and is edge-cached; the hillshade and the 3D mesh
 * read that instead, from one shared source.
 */

import {
  BASEMAP_ASSETS,
  BASEMAP_FLAVOR,
  BASEMAP_URL,
  INITIAL_VIEW,
  TERRAIN_TILEJSON,
  WORLD_IMAGERY_URL,
} from "./config.js";
import { cogRgbProtocol } from "./cog-rgb.js";

const protocol = new pmtiles.Protocol();

/* One transparent pixel, PNG-encoded, stretched over a tile that has none.
 *
 * A raster PMTiles archive stores no tile where the image is blank, and the
 * protocol answers for those with `data: null`. MapLibre's RasterTileSource
 * only marks a tile loaded inside `if (response && response.data)` and has no
 * else branch, so a missing tile is left in `loading` for ever: never drawn,
 * never retried, and the coarser parent tile stays magnified in its place. The
 * archives are sparse rectangles over a sparse set of MGRS tiles — 12 of 36
 * sampled z11 tiles are absent from the Alps build — so this reads as patches
 * near the edge of the data that never sharpen as you zoom in.
 *
 * Answering with a blank tile says what the absence means, and lets MapLibre
 * finish. Only raster archives need it: for vector tiles the protocol already
 * returns an empty buffer rather than null, so the tile grid is unaffected. */
const BLANK_TILE = Uint8Array.from(
  atob("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGNgAAIAAAUAAXpeqz8AAAAASUVORK5CYII="),
  (character) => character.charCodeAt(0),
);

maplibregl.addProtocol("pmtiles", async (params, abortController) => {
  const result = await protocol.tile(params, abortController);
  if (params.type !== "json" && result?.data === null) return { data: BLANK_TILE };
  return result;
});

/* Registered beside it rather than instead of it: a manifest can offer the same
 * layer as a pre-styled PMTiles archive and as the float COG it was styled
 * from, and the panel switches between them. One archive through a ramp or two
 * combined into false colour both go through this one protocol — see
 * js/cog-rgb.js. Registering is free: the reader it needs is not fetched until
 * a tile is asked for. */
maplibregl.addProtocol("glace-rgb", cogRgbProtocol);

/* The basemap style is generated by @protomaps/basemaps rather than hand-written:
 * it is ~100 layers, and the flavor decides all of their colours. Data layers are
 * appended after it, so they draw on top. */
const flavor = basemaps.namedFlavor(BASEMAP_FLAVOR);
const DARK_LABEL_PAINT = {
  "text-color": "#f8fafc",
  "text-halo-color": "rgba(0, 0, 0, 0.9)",
  "text-halo-width": 2,
  "text-halo-blur": 0.5,
};
const darkVectorBasemap = new Set(["black", "dark"]).has(BASEMAP_FLAVOR);
const basemapLayers = basemaps.layers("protomaps", flavor, { lang: "en" }).map((layer) => {
  if (darkVectorBasemap && layer.type === "symbol" && layer.layout?.["text-field"] !== undefined) {
    return { ...layer, paint: { ...layer.paint, ...DARK_LABEL_PAINT } };
  }
  return layer;
});
const style = {
  version: 8,
  /* `globe` is not "always a globe": MapLibre expands the bare type into a zoom
   * interpolation — vertical-perspective at z11, mercator from z12 — so the
   * earth is round while the whole arc is in view and flat by the time anyone
   * is reading a glacier. The page opens around z6, so that is the state a
   * first visit lands in.
   *
   * Terrain is supported under it (the shaders carry combined GLOBE/TERRAIN3D
   * paths), so this does not cost the 3D button anything. Two things are not:
   * fog matrices, which the style does not use, and easing around a point,
   * which downgrades zoom-toward-the-cursor to zoom-toward-the-centre while the
   * globe is on screen. */
  projection: { type: "globe" },
  glyphs: `${BASEMAP_ASSETS}/fonts/{fontstack}/{range}.pbf`,
  sprite: `${BASEMAP_ASSETS}/sprites/v4/${BASEMAP_FLAVOR}`,
  sources: {
    protomaps: {
      type: "vector",
      url: BASEMAP_URL,
      /* The basemap is always on the map, so this is the attribution that is
       * always shown, and the three credits that are not tied to a toggle ride
       * along in it. They stay in one string deliberately: MapLibre sorts
       * attributions by length before joining them, so three separate entries
       * would be scattered through the line, while one entry keeps its own
       * order. MapLibre credits the renderer rather than a source, but there is
       * no other entry guaranteed to be present. */
      attribution:
        '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>' +
        ' | <a href="https://protomaps.com">Protomaps</a>' +
        ' | <a href="https://maplibre.org">MapLibre</a>',
    },
  },
  layers: basemapLayers,
};

/* The vector basemap can be replaced by imagery without replacing the whole
 * style (which would discard every lazily added data layer). Remember the
 * original visibility of its non-label layers so switching back restores the
 * generated Protomaps style exactly. Symbols are intentionally excluded: the
 * separate label checkbox controls them, including over World Imagery. */
const VECTOR_BASEMAP_LAYERS = new Map(
  style.layers
    .filter((layer) => layer.type !== "symbol")
    .map((layer) => [layer.id, layer.layout?.visibility ?? "visible"]),
);
const LABEL_PAINT_PROPERTIES = Object.keys(DARK_LABEL_PAINT);
const VECTOR_LABEL_PAINT = new Map(
  style.layers
    .filter(
      (layer) =>
        layer.type === "symbol" &&
        layer.source === "protomaps" &&
        layer.layout?.["text-field"] !== undefined,
    )
    .map((layer) => [
      layer.id,
      Object.fromEntries(
        LABEL_PAINT_PROPERTIES.map((property) => [property, layer.paint?.[property] ?? null]),
      ),
    ]),
);
const WORLD_IMAGERY_SOURCE = "world-imagery";
const WORLD_IMAGERY_LAYER = "world-imagery";

export const map = new maplibregl.Map({
  container: "map",
  style,
  center: INITIAL_VIEW.center,
  zoom: INITIAL_VIEW.zoom,
  maxZoom: INITIAL_VIEW.maxZoom,
  // The view lives in the URL, so a hash overrides the opening view above.
  hash: true,
  attributionControl: false,
});
map.addControl(new maplibregl.NavigationControl({ visualizePitch: false }), "top-right");
map.addControl(new maplibregl.ScaleControl({ maxWidth: 120, unit: "metric" }), "bottom-left");
map.addControl(new maplibregl.AttributionControl({ compact: true }), "bottom-right");

map.on("error", (event) => {
  if (event.error) console.warn("maplibre:", event.error.message);
});

/* `load` fires exactly once, and only when every source has finished loading —
 * which the first data layer immediately undoes, so from then on
 * `isStyleLoaded()` is false while tiles stream but `load` can never fire again.
 * Anything waiting on it in that window waits forever. Adding a source needs
 * only the style to be parsed, which is what `style.load` reports; the promise
 * is built here, before the style can possibly have loaded.
 *
 * Every control that touches the map awaits this, which is also what makes the
 * page usable while the basemap is still coming down: a box ticked during those
 * first seconds is honoured when the style arrives instead of being dropped. */
export const styleReady = new Promise((resolve) => map.once("style.load", resolve));

/* ---------- layer ordering ---------- */

function firstSymbolLayer() {
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol") return layer.id;
  }
  return undefined;
}

/* Draw order, bottom to top:
 *
 *   basemap fills · GLACE rasters · hillshade · vector overlays · basemap labels
 *
 * Everything above the basemap is created lazily, the first time its control is
 * switched on, so the layers arrive in whatever order the reader clicks. That
 * makes "whichever was added last ends up on top" useless as a stacking rule:
 * shaded relief has to sit over the data whether the box was ticked before or
 * after a year was chosen, and glacier outlines have to sit over the relief.
 *
 * So each layer says what kind it is instead, and is inserted before the lowest
 * layer already on the map that must stay above it — falling through to the
 * basemap's first symbol layer, which is what keeps the labels on top of all of
 * it. */
const STACK = ["data", "hillshade", "overlay"];

/* Layer id -> kind. Entries for removed layers are left behind rather than
 * swept: the lookup only ever asks about ids the style still has. */
const layerKinds = new Map();

export function addStacked(kind, layer) {
  const above = STACK.slice(STACK.indexOf(kind) + 1);
  const before =
    map.getStyle().layers.find((other) => above.includes(layerKinds.get(other.id)))?.id ??
    firstSymbolLayer();
  map.addLayer(layer, before);
  layerKinds.set(layer.id, kind);
}

/* ---------- basemap ---------- */

function ensureWorldImagery() {
  if (!map.getSource(WORLD_IMAGERY_SOURCE)) {
    map.addSource(WORLD_IMAGERY_SOURCE, {
      type: "raster",
      tiles: [WORLD_IMAGERY_URL],
      tileSize: 256,
      maxzoom: 19,
      attribution:
        'Tiles © Esri, Maxar, Earthstar Geographics, and the GIS User Community' +
        ' | <a href="https://maplibre.org">MapLibre</a>',
    });
  }
  if (!map.getLayer(WORLD_IMAGERY_LAYER)) {
    /* Below the first generated basemap layer, so imagery remains the floor of
     * the stack and GLACE data, relief, overlays and labels all stay above it. */
    map.addLayer(
      {
        id: WORLD_IMAGERY_LAYER,
        type: "raster",
        source: WORLD_IMAGERY_SOURCE,
        layout: { visibility: "none" },
      },
      map.getStyle().layers[0]?.id,
    );
  }
}

export async function setBasemap(value) {
  await styleReady;
  const imagery = value === "imagery";
  if (imagery) ensureWorldImagery();
  for (const [id, visibility] of VECTOR_BASEMAP_LAYERS) {
    map.setLayoutProperty(id, "visibility", imagery ? "none" : visibility);
  }
  if (map.getLayer(WORLD_IMAGERY_LAYER)) {
    map.setLayoutProperty(WORLD_IMAGERY_LAYER, "visibility", imagery ? "visible" : "none");
  }
  /* World Imagery varies from snow to near-black forest within one viewport, so
   * its labels need a fixed light face and dark halo. On the vector background,
   * restore the flavor's own paint (already strengthened for dark flavors). */
  for (const [id, paint] of VECTOR_LABEL_PAINT) {
    for (const property of LABEL_PAINT_PROPERTIES) {
      map.setPaintProperty(id, property, imagery ? DARK_LABEL_PAINT[property] : paint[property]);
    }
  }
}

/* ---------- basemap labels ---------- */

/* The basemap's symbol layers are the only ones that compete with the data for
 * legibility, so the toggle hides those rather than the whole basemap. */
export async function toggleBasemapLabels(on) {
  await styleReady;
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol" && layer.source === "protomaps") {
      map.setLayoutProperty(layer.id, "visibility", on ? "visible" : "none");
    }
  }
}

/* ---------- terrain ---------- */

/* One `raster-dem` source feeds both the shaded relief and the 3D mesh, so
 * whichever is switched on first pays for the tilejson and the tiles and the
 * other rides along. Created on first use rather than at startup: it is a
 * network cost nobody who leaves both switched off should pay. */
const TERRAIN_SOURCE = "terrain";

function ensureTerrainSource() {
  if (map.getSource(TERRAIN_SOURCE)) return;
  map.addSource(TERRAIN_SOURCE, {
    type: "raster-dem",
    url: TERRAIN_TILEJSON,
    /* Shown while the DEM is actually being drawn — MapLibre credits a source
     * when a visible layer uses it (the hillshade) or when it carries the
     * terrain (3D), so this appears for either and goes away when both are
     * off, without the page having to track it. */
    attribution: '© <a href="https://mapterhorn.com/attribution/">Mapterhorn</a>',
  });
}

/* ---------- hillshade ---------- */

const HILLSHADE_LAYER = "hillshade";

const hillshade = { on: false, strength: 0.55 };

/* MapLibre has no layer blend modes, so a literal "multiply" is not available.
 * The equivalent for shaded relief is a hillshade whose highlights are fully
 * transparent and whose shadows are black: lit slopes leave the data untouched
 * and shaded slopes darken it, which is what multiplying by a shading layer
 * does. There is no `hillshade-opacity` either, so the strength slider drives
 * the alpha of the shadow and accent colours. */
function hillshadePaint(strength) {
  return {
    "hillshade-method": "igor",
    "hillshade-illumination-direction": 315,
    "hillshade-exaggeration": 0.5,
    "hillshade-highlight-color": "rgba(255, 255, 255, 0)",
    "hillshade-shadow-color": `rgba(0, 0, 0, ${strength.toFixed(3)})`,
    "hillshade-accent-color": `rgba(0, 0, 0, ${(strength * 0.5).toFixed(3)})`,
  };
}

function ensureHillshade() {
  if (map.getLayer(HILLSHADE_LAYER)) return;
  ensureTerrainSource();
  addStacked("hillshade", {
    id: HILLSHADE_LAYER,
    type: "hillshade",
    source: TERRAIN_SOURCE,
    layout: { visibility: "none" },
    paint: hillshadePaint(hillshade.strength),
  });
}

export async function setHillshade(on) {
  hillshade.on = on;
  await applyHillshade();
}

export async function setHillshadeStrength(strength) {
  hillshade.strength = strength;
  await applyHillshade();
}

async function applyHillshade() {
  await styleReady;
  // Nothing to create while the box has never been ticked, and nothing to
  // update either — the paint is read when the layer is finally built.
  if (!hillshade.on && !map.getLayer(HILLSHADE_LAYER)) return;
  ensureHillshade();
  map.setLayoutProperty(HILLSHADE_LAYER, "visibility", hillshade.on ? "visible" : "none");
  for (const [property, value] of Object.entries(hillshadePaint(hillshade.strength))) {
    map.setPaintProperty(HILLSHADE_LAYER, property, value);
  }
}

/* ---------- 3D ---------- */

/* Enabling 3D drapes the map over the DEM and tilts the camera in one gesture,
 * and disabling it puts the camera back flat — the behaviour the button
 * promises, rather than terrain quietly switched on under an unchanged
 * overhead view where it would be invisible. The tilt is animated because the
 * jump reads as the page reloading.
 *
 * 60° is MapLibre's default `maxPitch`, so the slant does not need the map to
 * be constructed with a raised limit. */
const THREE_D_PITCH = 60;
const THREE_D_DURATION_MS = 600;
const TERRAIN_EXAGGERATION = 1;

const view = { threeD: false };
let threeDButton = null;

/* `tilt: false` switches the mesh without moving the camera, which is what the
 * restore at the bottom of this file needs: the pitch is already where the
 * #hash put it, and easing to 60° would round every shared link off to the
 * same view. Pressing the button always tilts. */
export async function setThreeD(on, { tilt = true } = {}) {
  view.threeD = on;
  syncThreeDButton();
  await styleReady;
  if (on) {
    ensureTerrainSource();
    map.setTerrain({ source: TERRAIN_SOURCE, exaggeration: TERRAIN_EXAGGERATION });
  } else {
    // Terrain is dropped, but the source stays for the hillshade and for the
    // next time the button is pressed.
    map.setTerrain(null);
  }
  // The mesh is raised before the camera moves, so the tilt does not play out
  // over a surface that is still flat.
  if (tilt) map.easeTo({ pitch: on ? THREE_D_PITCH : 0, duration: THREE_D_DURATION_MS });
}

/* MapLibre ships a `TerrainControl`, but it draws a mountain glyph and only
 * flips `setTerrain`. This is the same button with the label the design asks
 * for and the camera move above. It borrows MapLibre's own control classes, so
 * it renders as one more button in the stack under the navigation control
 * rather than as something bolted beside it. */
class ThreeDControl {
  onAdd() {
    this.container = document.createElement("div");
    this.container.className = "maplibregl-ctrl maplibregl-ctrl-group";
    threeDButton = document.createElement("button");
    threeDButton.type = "button";
    threeDButton.className = "maplibregl-ctrl-3d";
    threeDButton.addEventListener("click", () => setThreeD(!view.threeD));
    this.container.append(threeDButton);
    syncThreeDButton();
    return this.container;
  }

  onRemove() {
    this.container.remove();
    threeDButton = null;
  }
}

/* The button names what the next press does, not the state it is in: "3D"
 * while the map is flat, "2D" once it is tilted. */
function syncThreeDButton() {
  if (!threeDButton) return;
  const action = view.threeD ? "Disable 3D terrain" : "Enable 3D terrain";
  threeDButton.textContent = view.threeD ? "2D" : "3D";
  threeDButton.title = action;
  threeDButton.setAttribute("aria-label", action);
  threeDButton.setAttribute("aria-pressed", String(view.threeD));
}

map.addControl(new ThreeDControl(), "top-right");

/* The view lives in the #hash, pitch included, so a link copied while tilted
 * comes back tilted. Terrain is not in the hash, so without this the recipient
 * would get the slant with a flat surface under it. */
if (map.getPitch() > 0) setThreeD(true, { tilt: false });
