/*
 * The map itself: the basemap style, layer ordering, and the two things layered
 * onto the basemap that are not data — the label toggle and the shaded relief.
 *
 * Everything on the map is a PMTiles archive read straight from object storage
 * over HTTP range requests — the GLACE rasters, the Protomaps basemap and the
 * Mapterhorn terrain. There is no tile server anywhere in the stack.
 */

import {
  BASEMAP_ASSETS,
  BASEMAP_FLAVOR,
  BASEMAP_URL,
  TERRAIN_TILEJSON,
} from "./config.js";

const protocol = new pmtiles.Protocol();
maplibregl.addProtocol("pmtiles", protocol.tile);

/* The basemap style is generated by @protomaps/basemaps rather than hand-written:
 * it is ~100 layers, and the flavor decides all of their colours. Data layers are
 * appended after it, so they draw on top. */
const flavor = basemaps.namedFlavor(BASEMAP_FLAVOR);
const style = {
  version: 8,
  glyphs: `${BASEMAP_ASSETS}/fonts/{fontstack}/{range}.pbf`,
  sprite: `${BASEMAP_ASSETS}/sprites/v4/${BASEMAP_FLAVOR}`,
  sources: {
    protomaps: {
      type: "vector",
      url: `pmtiles://${BASEMAP_URL}`,
      attribution:
        '<a href="https://protomaps.com">Protomaps</a> © <a href="https://openstreetmap.org">OpenStreetMap</a>',
    },
  },
  layers: basemaps.layers("protomaps", flavor, { lang: "en" }),
};

export const map = new maplibregl.Map({
  container: "map",
  style,
  center: [10.4, 46.5],
  zoom: 6.2,
  maxZoom: 14,
  hash: true,
  attributionControl: false,
});
map.addControl(new maplibregl.NavigationControl({ visualizePitch: false }), "top-right");
map.addControl(new maplibregl.ScaleControl({ maxWidth: 120, unit: "metric" }), "bottom-right");
map.addControl(new maplibregl.AttributionControl({ compact: true }), "bottom-right");

map.on("error", (event) => {
  if (event.error) console.warn("maplibre:", event.error.message);
});

/* `load` fires exactly once, and only when every source has finished loading —
 * which the first data layer immediately undoes, so from then on
 * `isStyleLoaded()` is false while tiles stream but `load` can never fire again.
 * Anything waiting on it in that window waits forever. Adding a source needs
 * only the style to be parsed, which is what `style.load` reports; the promise
 * is built here, before the style can possibly have loaded.
 *
 * Every control that touches the map awaits this, which is also what makes the
 * page usable while the basemap is still coming down: a box ticked during those
 * first seconds is honoured when the style arrives instead of being dropped. */
export const styleReady = new Promise((resolve) => map.once("style.load", resolve));

/* ---------- layer ordering ---------- */

function firstSymbolLayer() {
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol") return layer.id;
  }
  return undefined;
}

/* Where a data layer goes: below the hillshade when there is one, and below the
 * basemap's labels either way. Order-independent on purpose — the hillshade is
 * created whenever it is first switched on, which may be before or after the
 * data layers exist, so "whichever was added last ends up on top" is not a safe
 * way to get shaded relief over the data. Inserting the hillshade before the
 * first symbol layer puts it above data layers that already exist; this puts
 * later data layers below a hillshade that already exists. */
export function dataInsertPoint() {
  return map.getLayer(HILLSHADE_LAYER) ? HILLSHADE_LAYER : firstSymbolLayer();
}

/* ---------- basemap labels ---------- */

/* The basemap's symbol layers are the only ones that compete with the data for
 * legibility, so the toggle hides those rather than the whole basemap. */
export async function toggleBasemapLabels(on) {
  await styleReady;
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol" && layer.source === "protomaps") {
      map.setLayoutProperty(layer.id, "visibility", on ? "visible" : "none");
    }
  }
}

/* ---------- hillshade ---------- */

const HILLSHADE_LAYER = "hillshade";
const TERRAIN_SOURCE = "terrain";

const terrain = { on: false, strength: 0.55 };

/* MapLibre has no layer blend modes, so a literal "multiply" is not available.
 * The equivalent for shaded relief is a hillshade whose highlights are fully
 * transparent and whose shadows are black: lit slopes leave the data untouched
 * and shaded slopes darken it, which is what multiplying by a shading layer
 * does. There is no `hillshade-opacity` either, so the strength slider drives
 * the alpha of the shadow and accent colours. */
function hillshadePaint(strength) {
  return {
    "hillshade-method": "igor",
    "hillshade-exaggeration": 0.9,
    "hillshade-highlight-color": "rgba(255, 255, 255, 0)",
    "hillshade-shadow-color": `rgba(0, 0, 0, ${strength.toFixed(3)})`,
    "hillshade-accent-color": `rgba(0, 0, 0, ${(strength * 0.5).toFixed(3)})`,
  };
}

/* Created on first use rather than at startup: the terrain tilejson and its
 * tiles are a network cost nobody who leaves the box unticked should pay. */
function ensureHillshade() {
  if (map.getSource(TERRAIN_SOURCE)) return;
  map.addSource(TERRAIN_SOURCE, { type: "raster-dem", url: TERRAIN_TILEJSON });
  map.addLayer(
    {
      id: HILLSHADE_LAYER,
      type: "hillshade",
      source: TERRAIN_SOURCE,
      layout: { visibility: "none" },
      paint: hillshadePaint(terrain.strength),
    },
    firstSymbolLayer(),
  );
}

export async function setHillshade(on) {
  terrain.on = on;
  await applyHillshade();
}

export async function setHillshadeStrength(strength) {
  terrain.strength = strength;
  await applyHillshade();
}

async function applyHillshade() {
  await styleReady;
  // Nothing to create while the box has never been ticked, and nothing to
  // update either — the strength is read when the layer is finally built.
  if (!terrain.on && !map.getLayer(HILLSHADE_LAYER)) return;
  ensureHillshade();
  map.setLayoutProperty(HILLSHADE_LAYER, "visibility", terrain.on ? "visible" : "none");
  for (const [property, value] of Object.entries(hillshadePaint(terrain.strength))) {
    map.setPaintProperty(HILLSHADE_LAYER, property, value);
  }
}
