/*
 * GLACE quick-look viewer.
 *
 * Everything on the map is a PMTiles archive read straight from object storage
 * over HTTP range requests — the GLACE rasters, the Protomaps basemap and the
 * Mapterhorn terrain. There is no tile server anywhere in the stack.
 *
 * Data layers come from `layers.json` (written by scripts/stac/build-pmtiles.py),
 * one per (product, polarization, year). Sources are added lazily on first use
 * and then only toggled, so scrubbing through years stays instant.
 *
 * The tile directory defaults to ./tiles and can be pointed anywhere with
 * ?tiles=<base-url>, which is how a GitHub Pages copy of this page reads
 * archives hosted on object storage.
 */

const params = new URLSearchParams(location.search);
const TILES_BASE = (params.get("tiles") || "tiles").replace(/\/$/, "");

/* Protomaps' free daily basemap build, mirrored on Source Cooperative.
 * Serves CORS `*` and honours range requests, so it can be read cross-origin. */
const BASEMAP_URL =
  params.get("basemap") ||
  "https://data.source.coop/protomaps/openstreetmap/v4.pmtiles";
const BASEMAP_FLAVOR = params.get("flavor") || "grayscale";
const ASSETS = "https://protomaps.github.io/basemaps-assets";

/* Mapterhorn global terrain, terrarium-encoded, 512 px WEBP tiles. */
const TERRAIN_TILEJSON = "https://tiles.mapterhorn.com/tilejson.json";
const TERRAIN_CREDIT = {
  title: "Mapterhorn Terrain Tiles",
  citation: "\u00a9 Mapterhorn",
  links: [
    { label: "Attribution", url: "https://mapterhorn.com/attribution/" },
    { label: "Data Access", url: "https://mapterhorn.com/data-access/" },
  ],
};

/* Icons are inline SVG rather than an icon font: the page has no build step and
 * one more CDN request for two glyphs is not worth it. The info mark is
 * MapLibre's own attribution glyph, reused verbatim so the per-layer buttons and
 * the control in the corner of the map read as the same thing. */
const ICONS = {
  info:
    '<svg viewBox="0 0 20 20" width="14" height="14" fill="currentColor" ' +
    'fill-rule="evenodd" aria-hidden="true"><path d="M4 10a6 6 0 1 0 12 0 6 6 0 1 0-12 0' +
    'm5-3a1 1 0 1 0 2 0 1 1 0 1 0-2 0m0 3a1 1 0 1 1 2 0v3a1 1 0 1 1-2 0"/></svg>',
  chevron:
    '<svg viewBox="0 0 12 12" width="12" height="12" fill="none" stroke="currentColor" ' +
    'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
    '<path d="M2.5 4.5 6 8 9.5 4.5"/></svg>',
};

const state = {
  manifest: null,
  product: null,
  pol: null,
  year: null,
  opacity: 1,
  hillshade: false,
  hillshadeStrength: 0.55,
  added: new Set(),
};

const el = (id) => document.getElementById(id);

function status(message) {
  const node = el("status");
  node.hidden = !message;
  node.textContent = message || "";
}

/* ---------- map ---------- */

const protocol = new pmtiles.Protocol();
maplibregl.addProtocol("pmtiles", protocol.tile);

/* The basemap style is generated by @protomaps/basemaps rather than hand-written:
 * it is ~100 layers, and the flavor decides all of their colours. Data layers are
 * appended after it, so they draw on top. */
const flavor = basemaps.namedFlavor(BASEMAP_FLAVOR);
const style = {
  version: 8,
  glyphs: `${ASSETS}/fonts/{fontstack}/{range}.pbf`,
  sprite: `${ASSETS}/sprites/v4/${BASEMAP_FLAVOR}`,
  sources: {
    protomaps: {
      type: "vector",
      url: `pmtiles://${BASEMAP_URL}`,
      attribution:
        '<a href="https://protomaps.com">Protomaps</a> © <a href="https://openstreetmap.org">OpenStreetMap</a>',
    },
  },
  layers: basemaps.layers("protomaps", flavor, { lang: "en" }),
};

const map = new maplibregl.Map({
  container: "map",
  style,
  center: [10.4, 46.5],
  zoom: 6.2,
  maxZoom: 14,
  hash: true,
  attributionControl: false,
});
map.addControl(new maplibregl.NavigationControl({ visualizePitch: false }), "top-right");
map.addControl(new maplibregl.ScaleControl({ maxWidth: 120, unit: "metric" }), "bottom-right");
map.addControl(new maplibregl.AttributionControl({ compact: true }), "bottom-right");

/* `load` fires exactly once, and only when every source has finished loading —
 * which boot() immediately undoes by adding the raster layers, so from then on
 * `isStyleLoaded()` is false while tiles stream but `load` can never fire again.
 * Anything waiting on it in that window waits forever. Adding a source needs
 * only the style to be parsed, which is what `style.load` reports; the promise
 * is built here, before the style can possibly have loaded. */
const styleReady = new Promise((resolve) => map.once("style.load", resolve));

/* ---------- data layers ---------- */

const layerId = (layer) => `glace-${layer.id}`;

/* Data sits above the basemap's land and water but below its labels, so place
 * every data layer before the first symbol layer. */
function firstSymbolLayer() {
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol") return layer.id;
  }
  return undefined;
}

function ensureLayer(layer) {
  if (state.added.has(layer.id)) return;
  map.addSource(layerId(layer), {
    type: "raster",
    url: `pmtiles://${TILES_BASE}/${layer.url}`,
    tileSize: 256,
    minzoom: layer.min_zoom,
    maxzoom: layer.max_zoom,
    bounds: layer.bounds,
    attribution: "GLACE / Copernicus Sentinel-1",
  });
  map.addLayer(
    {
      id: layerId(layer),
      type: "raster",
      source: layerId(layer),
      layout: { visibility: "none" },
      paint: { "raster-opacity": state.opacity, "raster-resampling": "nearest" },
    },
    firstSymbolLayer(),
  );
  state.added.add(layer.id);
}

function findLayer(product, pol, year) {
  return state.manifest.layers.find(
    (l) => l.product === product && l.polarization === pol && l.year === year,
  );
}

function render() {
  const active = findLayer(state.product, state.pol, state.year);
  for (const layer of state.manifest.layers) {
    if (!state.added.has(layer.id)) continue;
    const visible = active && layer.id === active.id;
    map.setLayoutProperty(layerId(layer), "visibility", visible ? "visible" : "none");
  }
  if (active) {
    ensureLayer(active);
    map.setLayoutProperty(layerId(active), "visibility", "visible");
    map.setPaintProperty(layerId(active), "raster-opacity", state.opacity);
    updateLegend(active);
    status("");
  } else {
    status(`No ${state.product} ${state.pol} layer for ${state.year}`);
    el("layer-info").textContent = "";
  }
  syncControls();
}

function updateLegend(layer) {
  el("legend-bar").style.background = `linear-gradient(to right, ${layer.colors.join(", ")})`;
  const unit = layer.units ? ` ${layer.units}` : "";
  const digits = Math.abs(layer.vmax - layer.vmin) < 5 ? 2 : 1;
  el("legend-min").textContent = layer.vmin.toFixed(digits) + unit;
  el("legend-max").textContent = layer.vmax.toFixed(digits) + unit;
  el("layer-info").textContent =
    `${layer.product} ${layer.polarization} ${layer.year} · ` +
    `z${layer.min_zoom}–${layer.max_zoom} · ${(layer.size_bytes / 1e6).toFixed(1)} MB · ${layer.cmap}`;
}

/* ---------- hillshade ---------- */

/* MapLibre has no layer blend modes, so a literal "multiply" is not available.
 * The equivalent for shaded relief is a hillshade whose highlights are fully
 * transparent and whose shadows are black: lit slopes leave the data untouched
 * and shaded slopes darken it, which is what multiplying by a shading layer
 * does. There is no `hillshade-opacity` either, so the strength slider drives
 * the alpha of the shadow and accent colours. */
function hillshadePaint(strength) {
  return {
    "hillshade-method": "igor",
    "hillshade-exaggeration": 0.9,
    "hillshade-highlight-color": "rgba(255, 255, 255, 0)",
    "hillshade-shadow-color": `rgba(0, 0, 0, ${strength.toFixed(3)})`,
    "hillshade-accent-color": `rgba(0, 0, 0, ${(strength * 0.5).toFixed(3)})`,
  };
}

function ensureHillshade() {
  if (map.getSource("terrain")) return;
  map.addSource("terrain", { type: "raster-dem", url: TERRAIN_TILEJSON });
  // Above the data (added first), below the basemap's labels.
  map.addLayer(
    {
      id: "hillshade",
      type: "hillshade",
      source: "terrain",
      layout: { visibility: "none" },
      paint: hillshadePaint(state.hillshadeStrength),
    },
    firstSymbolLayer(),
  );
}

function applyHillshade() {
  ensureHillshade();
  map.setLayoutProperty("hillshade", "visibility", state.hillshade ? "visible" : "none");
  const paint = hillshadePaint(state.hillshadeStrength);
  for (const [property, value] of Object.entries(paint)) {
    map.setPaintProperty("hillshade", property, value);
  }
  el("hillshade-strength-row").hidden = !state.hillshade;
}

/* ---------- controls ---------- */

function buildSegmented(node, values, key) {
  node.replaceChildren();
  for (const value of values) {
    const button = document.createElement("button");
    button.type = "button";
    button.setAttribute("role", "radio");
    button.textContent = value;
    button.dataset.value = value;
    button.addEventListener("click", () => {
      state[key] = value;
      render();
    });
    node.append(button);
  }
}

/* A product/polarization combination only exists for some years; the buttons
 * that would leave the current year empty are disabled rather than hidden, so
 * the control does not reflow while scrubbing. */
function syncControls() {
  for (const [node, key] of [
    [el("product"), "product"],
    [el("pol"), "pol"],
  ]) {
    for (const button of node.children) {
      const value = button.dataset.value;
      const exists =
        key === "product"
          ? findLayer(value, state.pol, state.year)
          : findLayer(state.product, value, state.year);
      button.setAttribute("aria-checked", String(state[key] === value));
      button.disabled = !exists && state[key] !== value;
    }
  }
  el("year-value").textContent = state.year;
  el("year").value = state.manifest.years.indexOf(state.year);
}

function initControls(manifest) {
  el("title").textContent = manifest.title;
  buildSegmented(el("product"), manifest.products, "product");
  buildSegmented(el("pol"), manifest.polarizations, "pol");

  const years = manifest.years;
  const slider = el("year");
  slider.min = 0;
  slider.max = Math.max(0, years.length - 1);
  slider.disabled = years.length < 2;
  slider.addEventListener("input", () => {
    state.year = years[Number(slider.value)];
    render();
  });
  el("year-ticks").replaceChildren();
  for (const year of years.length > 1 ? [years[0], years[years.length - 1]] : years) {
    const span = document.createElement("span");
    span.textContent = year;
    el("year-ticks").append(span);
  }

  el("opacity").addEventListener("input", (event) => {
    state.opacity = Number(event.target.value) / 100;
    el("opacity-value").textContent = `${event.target.value}%`;
    render();
  });

  el("hillshade-row").append(creditButton(TERRAIN_CREDIT.title, TERRAIN_CREDIT));
  el("hillshade").addEventListener("change", (event) => {
    state.hillshade = event.target.checked;
    applyHillshade();
  });
  el("hillshade-strength").addEventListener("input", (event) => {
    state.hillshadeStrength = Number(event.target.value) / 100;
    el("hillshade-strength-value").textContent = `${event.target.value}%`;
    applyHillshade();
  });

  el("basemap").addEventListener("change", (event) => toggleBasemapLabels(event.target.checked));
  el("grid").addEventListener("change", (event) => toggleGrid(event.target.checked));
}

/* The basemap's symbol layers are the only ones that compete with the data for
 * legibility, so the toggle hides those rather than the whole basemap. */
function toggleBasemapLabels(on) {
  for (const layer of map.getStyle().layers) {
    if (layer.type === "symbol" && layer.source === "protomaps") {
      map.setLayoutProperty(layer.id, "visibility", on ? "visible" : "none");
    }
  }
}

/* ---------- attribution ---------- */

/* Each third-party layer carries its own credit, reachable from an info mark
 * next to its toggle, rather than being folded into the map-wide attribution
 * control where a viewer cannot tell which layer it belongs to.
 *
 * The panel scrolls, so the popover is appended to the body and positioned
 * `fixed`: as an absolutely positioned child it would extend the panel's scroll
 * area rather than overflow it, and long citations would put a scrollbar on the
 * whole sidebar. Detached, it can also be wider than the panel. */
let creditBox = null;
let creditTimer = null;

const CREDIT_GAP_PX = 10;
const CREDIT_MARGIN_PX = 8;
const CREDIT_HIDE_DELAY_MS = 180;

function creditButton(title, credit) {
  const button = document.createElement("button");
  button.type = "button";
  button.className = "credit";
  button.innerHTML = ICONS.info;
  button.title = `${title} — attribution and licence`;
  button.setAttribute("aria-label", `${title}: attribution and licence`);
  // Hover for pointers, focus for keyboards, click for touch — where hover
  // does not exist and the button would otherwise be dead.
  button.addEventListener("mouseenter", () => showCredit(button, title, credit));
  button.addEventListener("focus", () => showCredit(button, title, credit));
  button.addEventListener("mouseleave", scheduleHideCredit);
  button.addEventListener("blur", scheduleHideCredit);
  button.addEventListener("click", (event) => {
    event.preventDefault();
    if (creditBox && creditBox.dataset.owner === title) hideCredit();
    else showCredit(button, title, credit);
  });
  return button;
}

function hideCredit() {
  clearTimeout(creditTimer);
  if (creditBox) {
    creditBox.remove();
    creditBox = null;
  }
}

/* A grace period, so the pointer can travel from the mark onto the box without
 * the box vanishing under it — the links inside have to stay reachable. */
function scheduleHideCredit() {
  clearTimeout(creditTimer);
  creditTimer = setTimeout(hideCredit, CREDIT_HIDE_DELAY_MS);
}

function creditRows(title, credit) {
  const rows = [`<strong>${credit.title || title}</strong>`];
  if (credit.citation) rows.push(`<span class="cite">${credit.citation}</span>`);
  if (credit.license) {
    rows.push(
      credit.license_url
        ? `License: <a href="${credit.license_url}" target="_blank" rel="noopener">${credit.license}</a>`
        : `License: ${credit.license}`,
    );
  }
  for (const link of credit.links || []) {
    rows.push(`<a href="${link.url}" target="_blank" rel="noopener">${link.label}</a>`);
  }
  return rows;
}

function showCredit(anchor, title, credit) {
  clearTimeout(creditTimer);
  if (creditBox && creditBox.dataset.owner === title) return;
  hideCredit();

  const box = document.createElement("div");
  box.className = "credit-popover";
  box.dataset.owner = title;
  box.innerHTML = creditRows(title, credit).join("<br>");
  box.addEventListener("mouseenter", () => clearTimeout(creditTimer));
  box.addEventListener("mouseleave", scheduleHideCredit);
  document.body.append(box);

  // Measured after insertion: the height depends on how far the citation wraps.
  const mark = anchor.getBoundingClientRect();
  const { width, height } = box.getBoundingClientRect();
  const left = Math.min(
    Math.max(mark.left + mark.width / 2 - width / 2, CREDIT_MARGIN_PX),
    window.innerWidth - width - CREDIT_MARGIN_PX,
  );
  const above = mark.top - height - CREDIT_GAP_PX;
  const below = above < CREDIT_MARGIN_PX;
  box.classList.toggle("below", below);
  box.style.left = `${left}px`;
  box.style.top = `${below ? mark.bottom + CREDIT_GAP_PX : above}px`;
  // The caret tracks the mark even when the box was clamped to the viewport.
  box.style.setProperty("--caret-x", `${mark.left + mark.width / 2 - left}px`);

  creditBox = box;
}

// A scroll or resize moves the mark out from under the box.
window.addEventListener("resize", hideCredit);
document.addEventListener("scroll", hideCredit, true);

/* ---------- glacier inventory overlays ---------- */

/* The inventories ship with the page rather than living on S3: simplified to
 * 10 m they come to a few MB, which is small enough to fetch whole and far
 * simpler than a second tiled format. Each is fetched only when first enabled. */
const inventoryState = new Map();

function removeInventory(id, entry) {
  for (const suffix of ["-casing", ""]) {
    const layer = `inv-line-${id}${suffix}`;
    if (map.getLayer(layer)) map.removeLayer(layer);
  }
  if (map.getSource(`inv-${id}`)) map.removeSource(`inv-${id}`);
  entry.loaded = false;
}

async function loadInventories() {
  let index;
  try {
    const response = await fetch("data/inventories.json");
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    index = await response.json();
  } catch {
    // Overlays are optional; the page works without them.
    return;
  }
  const node = el("inventories");
  node.replaceChildren();
  for (const entry of index.inventories) {
    inventoryState.set(entry.id, { ...entry, loaded: false });
    const row = document.createElement("div");
    row.className = "inventory";
    const box = document.createElement("input");
    box.type = "checkbox";
    box.id = `inv-${entry.id}`;
    const swatch = document.createElement("span");
    swatch.className = "swatch";
    swatch.style.background = entry.color;
    const label = document.createElement("label");
    label.htmlFor = box.id;
    // No forced break: the name wraps on its own where the panel is narrow, and
    // the span follows it inline so the row never runs to three lines.
    label.append(`${entry.title} `);
    const span = document.createElement("span");
    span.className = "span";
    span.textContent = `(${entry.span})`;
    label.append(span);
    box.addEventListener("change", () => toggleInventory(entry.id, box.checked));
    row.append(box, swatch, label, creditButton(entry.title, entry));
    node.append(row);
  }
  el("inventories-section").hidden = index.inventories.length === 0;

  const toggle = el("inventories-toggle");
  toggle.addEventListener("click", () => {
    const open = toggle.getAttribute("aria-expanded") === "true";
    toggle.setAttribute("aria-expanded", String(!open));
    toggle.querySelector(".chevron").classList.toggle("up", open);
    node.hidden = open;
  });
}

async function toggleInventory(id, on) {
  await styleReady;
  const entry = inventoryState.get(id);
  const lineId = `inv-line-${id}`;
  if (entry.loaded) {
    setInventoryVisibility(id, on);
    return;
  }
  if (!on) return;
  status(`Loading ${entry.title}…`);
  /* The browser pulls only the tiles the view covers, so the overlay draws as its
   * first tiles land rather than after the whole inventory has been fetched.
   * `source-layer` must match the layer name tippecanoe was given. */
  map.addSource(`inv-${id}`, { type: "vector", url: `pmtiles://data/${entry.url}` });
  /* Outlines only — a fill would hide the imagery the outline is there to be
   * compared against. The dark casing keeps them legible over both the pale and
   * the dark end of the colour ramps. */
  const sourceLayer = entry.source_layer || id;
  map.addLayer({
    id: `${lineId}-casing`,
    type: "line",
    source: `inv-${id}`,
    "source-layer": sourceLayer,
    paint: { "line-color": "rgba(0,0,0,0.55)", "line-width": 2.6, "line-opacity": 0.8 },
  });
  map.addLayer({
    id: lineId,
    type: "line",
    source: `inv-${id}`,
    "source-layer": sourceLayer,
    paint: {
      "line-color": entry.color,
      "line-width": ["interpolate", ["linear"], ["zoom"], 6, 0.6, 10, 1.2, 14, 2],
    },
  });
  entry.loaded = true;
  watchInventoryLoad(id, entry);
}

/* Because the source loads itself, success and failure arrive as map events
 * rather than as the resolution of a fetch. Both are one-shot: the listeners
 * take themselves off again so later tile activity on the source is ignored. */
function watchInventoryLoad(id, entry) {
  const sourceId = `inv-${id}`;
  const stop = () => {
    map.off("sourcedata", onData);
    map.off("error", onError);
  };
  const onData = (event) => {
    if (event.sourceId !== sourceId || !map.isSourceLoaded(sourceId)) return;
    stop();
    status("");
  };
  const onError = (event) => {
    if (event.sourceId !== sourceId) return;
    stop();
    // Roll back, so re-ticking the box is a fresh attempt rather than a no-op.
    removeInventory(id, entry);
    el(sourceId).checked = false;
    status(`${entry.title} unavailable (${event.error?.message ?? "load failed"})`);
  };
  map.on("sourcedata", onData);
  map.on("error", onError);
}

/* A one-pixel outline is nearly impossible to hit, so clicks are resolved
 * against a box around the pointer rather than the rendered line itself. This
 * also lets several overlapping inventories answer one click. */
const CLICK_RADIUS_PX = 8;
const GRID_LAYER = "grid-fill";
// Layer name inside tile-grid.pmtiles, set by webmap.TILE_GRID_LAYER. A vector
// layer whose `source-layer` does not match renders nothing and says nothing.
const GRID_SOURCE_LAYER = "grid";

/* One handler for every clickable overlay. Both the inventories and the catalog
 * grid are resolved against a box around the pointer rather than the rendered
 * geometry: a one-pixel outline is close to impossible to hit, and querying both
 * together means a single click reports everything under it in one popup rather
 * than racing two handlers to open competing ones. */
function clickableLayers() {
  const layers = [...inventoryState.values()]
    .filter((entry) => entry.loaded && el(`inv-${entry.id}`)?.checked)
    .map((entry) => `inv-line-${entry.id}`);
  if (gridLoaded && el("grid")?.checked) layers.push(GRID_LAYER);
  return layers.filter((id) => map.getLayer(id));
}

/* Every popup section reads the same way: a muted uppercase heading styled like
 * the panel's own field labels, then `label: value` lines. Fields whose value is
 * missing are dropped rather than shown empty. */
function popupSection(heading, fields) {
  const rows = fields
    .filter(([, value]) => value !== null && value !== undefined && value !== "")
    .map(([label, value]) => `<div><span class="pk">${label}:</span> ${value}</div>`);
  return `<div class="pop-head">${heading}</div>${rows.join("")}`;
}

const percent = (value) =>
  value === null || value === undefined ? null : `${(Number(value) * 100).toFixed(1)} %`;

function inventoryRow(feature) {
  const entry = inventoryState.get(feature.layer.id.replace("inv-line-", ""));
  const props = feature.properties;
  // Paul et al. ships no names but does carry its own glacier number, so each
  // inventory is described by whichever identifier it actually has.
  const identity =
    props.glacier_nr === undefined
      ? ["Glacier name", props.name || "No name provided"]
      : ["Glacier number", props.glacier_nr];
  return popupSection(entry.title, [
    identity,
    ["Acquisition year", props.year],
  ]);
}

/* The tile name is a UTM zone, a latitude band and the 100 km square, e.g.
 * 31TFJ68 — so the zone the tile is projected in can be read straight off it.
 * Bands C-M are the southern hemisphere, N-X the northern. */
function utmZone(tile) {
  const match = /^(\d{1,2})([C-HJ-NP-X])/.exec(tile || "");
  if (!match) return null;
  return `${Number(match[1])}${match[2] >= "N" ? "N" : "S"}`;
}

function gridRow(feature) {
  const props = feature.properties;
  return popupSection("MGRS tile", [
    ["Tile identifier", props.tile],
    ["UTM zone", utmZone(props.tile)],
    ["Glacier fraction", percent(props.glacier_fraction)],
  ]);
}

map.on("click", (event) => {
  const layers = clickableLayers();
  if (!layers.length) return;

  const { x, y } = event.point;
  const hits = map.queryRenderedFeatures(
    [
      [x - CLICK_RADIUS_PX, y - CLICK_RADIUS_PX],
      [x + CLICK_RADIUS_PX, y + CLICK_RADIUS_PX],
    ],
    { layers },
  );
  if (!hits.length) return;

  // A box this size often clips the same outline more than once; keep the first
  // hit per layer, and let the tile grid trail the inventories as context.
  const seen = new Set();
  const rows = [];
  let grid = null;
  for (const hit of hits) {
    if (seen.has(hit.layer.id)) continue;
    seen.add(hit.layer.id);
    if (hit.layer.id === GRID_LAYER) grid = gridRow(hit);
    else rows.push(inventoryRow(hit));
  }
  if (grid) rows.push(grid);
  new maplibregl.Popup().setLngLat(event.lngLat).setHTML(rows.join("<hr>")).addTo(map);
});

/* Casing and line must move together when visibility changes. */
function setInventoryVisibility(id, on) {
  const visibility = on ? "visible" : "none";
  for (const suffix of ["-casing", ""]) {
    const layer = `inv-line-${id}${suffix}`;
    if (map.getLayer(layer)) map.setLayoutProperty(layer, "visibility", visibility);
  }
}

/* ---------- tile-grid overlay ---------- */

let gridLoaded = false;

async function toggleGrid(on) {
  const visibility = on ? "visible" : "none";
  if (gridLoaded) {
    for (const id of ["grid-fill", "grid-line"]) {
      map.setLayoutProperty(id, "visibility", visibility);
    }
    return;
  }
  if (!on) return;
  /* Same delivery as everything else on the page: a vector archive read by
   * range request. Built only to z10 — the footprints are 110 km squares, and
   * MapLibre overzooms a vector source past its maximum for hit-testing as
   * well as for drawing. */
  map.addSource("grid", { type: "vector", url: `pmtiles://${TILES_BASE}/tile-grid.pmtiles` });
  map.addLayer({
    id: "grid-fill",
    type: "fill",
    source: "grid",
    "source-layer": GRID_SOURCE_LAYER,
    paint: {
      // Shade each MGRS tile by how much of it the inventory calls glacier.
      // White rather than the panel's blue: the data ramps run through blue at
      // one end and grey-white at the other, and only white keeps the grid
      // legible over both without being mistaken for the data itself.
      "fill-color": [
        "interpolate",
        ["linear"],
        ["coalesce", ["get", "glacier_fraction"], 0],
        0, "rgba(255,255,255,0.04)",
        0.25, "rgba(255,255,255,0.30)",
      ],
    },
  });
  map.addLayer({
    id: "grid-line",
    type: "line",
    source: "grid",
    "source-layer": GRID_SOURCE_LAYER,
    paint: { "line-color": "#ffffff", "line-width": 0.6, "line-opacity": 0.7 },
  });
  gridLoaded = true;
  watchGridLoad();
}

/* The archive is fetched lazily by the pmtiles protocol, so a missing or broken
 * one surfaces as a map error rather than as a throw from addSource. Without
 * this the checkbox would stay ticked over an overlay that never appears. */
function watchGridLoad() {
  const onError = (event) => {
    if (event.sourceId !== "grid") return;
    map.off("error", onError);
    for (const id of ["grid-fill", "grid-line"]) {
      if (map.getLayer(id)) map.removeLayer(id);
    }
    if (map.getSource("grid")) map.removeSource("grid");
    gridLoaded = false;
    el("grid").checked = false;
    status("Tile grid unavailable — rerun the build with --items-parquet");
  };
  const onData = (event) => {
    if (event.sourceId !== "grid" || !map.isSourceLoaded("grid")) return;
    map.off("sourcedata", onData);
    map.off("error", onError);
  };
  map.on("sourcedata", onData);
  map.on("error", onError);
}

/* ---------- boot ---------- */

async function boot() {
  status("Loading layers…");
  let manifest;
  try {
    const response = await fetch(`${TILES_BASE}/layers.json`);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    manifest = await response.json();
  } catch (error) {
    status(`Could not load ${TILES_BASE}/layers.json — ${error.message}`);
    return;
  }
  if (!manifest.layers.length) {
    status("The manifest holds no layers.");
    return;
  }

  state.manifest = manifest;
  const first = manifest.layers[0];
  state.product = first.product;
  state.pol = first.polarization;
  state.year = manifest.years[manifest.years.length - 1];
  if (!findLayer(state.product, state.pol, state.year)) state.year = first.year;

  initControls(manifest);
  for (const layer of manifest.layers) ensureLayer(layer);
  ensureHillshade();
  render();

  // Frame the data the first time the page is opened without a #hash.
  if (!location.hash) {
    const bounds = manifest.layers.reduce(
      (acc, l) => [
        Math.min(acc[0], l.bounds[0]), Math.min(acc[1], l.bounds[1]),
        Math.max(acc[2], l.bounds[2]), Math.max(acc[3], l.bounds[3]),
      ],
      [180, 90, -180, -90],
    );
    map.fitBounds(bounds, { padding: { top: 40, bottom: 40, left: 324, right: 40 }, animate: false });
  }
}

// The inventory list is independent of the map and the raster manifest, so it
// is built at once: waiting for them made the panel jump as it grew.
loadInventories();

map.on("load", boot);
map.on("error", (event) => {
  if (event.error) console.warn("maplibre:", event.error.message);
});
